version: '3.8'
services:
  docker1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker1:latest
    container_name: docker1
    ports:
      - 5000:80
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'
